saykit.GameEvent.CAMERA_ZOOM = 'CAMERA_ZOOM';
saykit.GameEvent.CAMERA_ADD_TARGET = 'CAMERA_ADD_TARGET';
saykit.GameEvent.CAMERA_DELETE_TARGET = 'CAMERA_DELETE_TARGET';
saykit.GameEvent.CAMERA_SWITCH_TARGET = 'CAMERA_SWITCH_TARGET';

saykit.GameEvent.CAMERA_MOVE_TO_TARGET = 'CAMERA_MOVE_TO_TARGET';
